### ISSUE TITLE
RFID / Arduino

### ISSUE THREAD

**Issue by cybercamphackathon** [ferdinan4/RFID-Security#10]
The arduino should be in charge of validating if the device is the expected one (which tokens do you use to verify that). And it is currently used only to colorize some leds. Making those checks in the app doesn't makes much sense, because this can be manipulated with a MiM attack or just by modifying the app itself.

**Comment by ferdinan4** [comment]
The arduino is an "extra" that we will used in the Demo of 05-12-2016 simulating an access control, for that reason we don't check any token, and currently used to colorize some leds...

If you have any doubt please let us known.
